### PR TITLE
Add widecolumn for oom and pushdown for oom

### PR DESCRIPTION
**Pull request by jinwhu**
### First-time contributors' checklist 

- [x] I've signed [**Contributor License Agreement**](https://cla-assistant.io/pingcap/docs) that's required for repo owners to accept my contribution.

### What is the related PR or file link(s)?

- This PR is translated from:
- Other reference link(s):

### Do your changes match any of the following descriptions?

- [ ] Delete files
- [ ] Change aliases

### CODE REVIEW

**Review by jackysp — APPROVED** [review]
LGTM

**Review by jackysp — APPROVED** [review]
LGTM

**Comment by jackysp** [comment]
PTAL @TomShawn

**Comment by TomShawn** [comment]
@jackysp Please merge it again after adding the require-LGT1 label.

**Pull request merged**
