### PR TITLE
Fix the object of description.

### PR DESCRIPTION
**Pull request by Laitr0n**
Python --> Golang

### First-time contributors' checklist 

- [x] I've signed [**Contributor License Agreement**](https://cla-assistant.io/pingcap/docs) that's required for repo owners to accept my contribution.

### What is changed, added or deleted? (Required)
Fix error of describe program language. Change Python to Golang.

### Which TiDB version(s) do your changes apply to? (Required)
all.

### What is the related PR or file link(s)?

- This PR is translated from:
- Other reference link(s):

### Do your changes match any of the following descriptions?

- [ ] Delete files
- [ ] Change aliases

### CODE REVIEW

**Review by TomShawn — APPROVED** [review]
LGTM

**Comment by TomShawn** [comment]
@Laitr0n Can we merge it?

**Comment by Laitr0n** [comment]
> @Laitr0n Can we merge it?

Yes. can-merge.

**Pull request merged**
