### PR TITLE
Add tdds documents

### PR DESCRIPTION
**Pull request by jackysp**
### First-time contributors' checklist 

- [x] I've signed [**Contributor License Agreement**](https://cla-assistant.io/pingcap/docs) that's required for repo owners to accept my contribution.

### What is changed, added or deleted? (Required)
Add the new content for appdev.

### What is the related PR or file link(s)?

- This PR is translated from:
- Other reference link(s):

### Do your changes match any of the following descriptions?

- [ ] Delete files
- [ ] Change aliases

### CODE REVIEW

**Comment by jackysp** [comment]
PTAL @it2911 @TomShawn

**Comment by jackysp** [comment]
\cc @jinwhu

**Review by jinwhu — APPROVED** [review]
lgtm

**Review by TomShawn — APPROVED** [review]

**Review by bb7133 — APPROVED** [review]

**Pull request merged**
